#!/bin/sh

op=$1
name=$2

abort() {
  test -n $* && echo $*
  exit 1
}

test -z $name && abort "Please specify sandbox name"

case "$op" in
"clone")
  mkdir "$name" && cd "$name" || abort

  cleanup() {
    cd ..
    rm -rf "$name"
    abort
  }

  git init
  git remote add sandbox git@github.com:eldargab/sandbox.git -t "$name"
  git fetch sandbox && git checkout -b master "sandbox/$name" || cleanup
  echo "Done!"
  ;;
"init")
  git init || abort
  git remote add sandbox git@github.com:eldargab/sandbox.git -t "$name"
  git add -A && git commit -m "Initial commit" && git push -u sandbox master:$name && echo "Done!"
  ;;
*) abort "Unknown command: $op"
  ;;
esac
